spring.application.name=sors-backend
server.port=8080
server.servlet.context-path=/api
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secret=uep_sors_super_secret_jwt_key_minimum_32_chars
jwt.expiration=86400000
logging.level.root=INFO
logging.level.com.uep.sors=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=uepsors.noreply@gmail.com
spring.mail.password=arfu ojgj egcf bbek
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true